<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Not Now</name>
   <tag></tag>
   <elementGuidId>557700d4-4417-4091-b80e-d093d0c1d72c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._a9--._a9_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount_0_0_Ji']/div/div/div[3]/div/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>338e7f4f-26f4-4812-a426-3d28abe02ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_a9-- _a9_1</value>
      <webElementGuid>37872e94-28c1-4f99-b3dc-a56a02d6bef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e7b0b1f9-8c45-4501-9683-acd1aa644533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Not Now</value>
      <webElementGuid>1b42ae90-6e08-4ff7-95ad-a42387f9f678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_Ji&quot;)/div[1]/div[1]/div[3]/div[1]/div[@class=&quot;x1n2onr6 xzkaem6&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf xg6iff7 x1n2onr6&quot;]/div[@class=&quot;x1uvtmcs x4k7w5x x1h91t0o x1beo9mf xaigb6o x12ejxvf x3igimt xarpa2k xedcshv x1lytzrv x1t2pt76 x7ja8zs x1n2onr6 x1qrby5j x1jfb8zj&quot;]/div[@class=&quot;x1qjc9v5 x9f619 x78zum5 xdt5ytf x1iyjqo2 xl56j7k&quot;]/div[@class=&quot;x1cy8zhl x9f619 x78zum5 xl56j7k x2lwn1j xeuugli x47corl&quot;]/div[@class=&quot;x1ja2u2z x1afcbsf x1a2a7pz x6ikm8r x10wlt62 x71s49j x6s0dn4 x78zum5 xdt5ytf xl56j7k x1n2onr6&quot;]/div[@class=&quot;xs83m0k xl56j7k x1sy10c2 x1h5jrl4 xieb3on xmn8rco x1iy3rx x1n2onr6 x1hfn5x7 x13wlyjk xw8ag78 x1v7wizp xc7qz2s xa3vuyk&quot;]/div[@class=&quot;x7r02ix xf1ldfh x131esax xdajt7p xxfnqb6 xb88tzc xw2csxc x1odjw0f x5fp0pe&quot;]/div[1]/div[@class=&quot;_a9-v&quot;]/div[@class=&quot;_a9-z&quot;]/button[@class=&quot;_a9-- _a9_1&quot;]</value>
      <webElementGuid>98a816ce-301b-4f8a-aecb-fe284607aac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_Ji']/div/div/div[3]/div/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div[3]/button[2]</value>
      <webElementGuid>beff1eb0-0a4a-47c7-85b4-f2286d8f3e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turn On'])[1]/following::button[1]</value>
      <webElementGuid>d733edef-280a-4357-a63c-22d88f479b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Know right away when people follow you or like and comment on your photos.'])[1]/following::button[2]</value>
      <webElementGuid>f057190f-9f9f-4555-8562-b0b9a679420f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Not Now']/parent::*</value>
      <webElementGuid>abfa32ca-a8c8-401a-8965-b323d64fa046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>07f0f4e7-f068-46d9-9335-7b280edaa7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Not Now' or . = 'Not Now')]</value>
      <webElementGuid>857793d5-b392-40cf-80c2-47d7695536e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_r6']/div/div/div[3]/div/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div[3]/button[2]</value>
      <webElementGuid>0059e2a3-9fe4-4b89-a046-b633ce700cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>a068a9a7-0668-423c-8ade-64b9ce1cfda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>b8e4e6df-0ae6-4f29-94ff-54f59d1927c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
