<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Sorry, your password was incorrect. Please double-check your password</name>
   <tag></tag>
   <elementGuidId>68e8f91c-8f07-464f-9918-7b692db68175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#slfErrorAlert</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='slfErrorAlert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bcbfe2f1-5849-4529-b321-c492381f44a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a19bc902-3617-46ed-b353-6234b1ef017b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slfErrorAlert</value>
      <webElementGuid>ca04b467-f366-4c4b-9599-c013ee3a680d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>3979431d-4ccb-488b-8f9c-e3de919b7d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sorry, your password was incorrect. Please double-check your password.</value>
      <webElementGuid>1869b0e8-2a81-4522-a346-b41944fa9509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slfErrorAlert&quot;)</value>
      <webElementGuid>9d05a7fb-ddfe-4084-9cb2-d4ba7242ee75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='slfErrorAlert']</value>
      <webElementGuid>bad3fd74-f68a-4f4c-af94-44003570bd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[2]/p</value>
      <webElementGuid>5f299c80-608b-4651-918e-ef5c6d31c287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in with Facebook'])[1]/following::p[1]</value>
      <webElementGuid>523f5dce-b024-4fb9-838a-da21f9d8ace4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/following::p[1]</value>
      <webElementGuid>7a414719-718a-4e31-9ce7-36f768398c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/preceding::p[1]</value>
      <webElementGuid>587bf57c-bd08-4585-8aba-6db68fbbeab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::p[1]</value>
      <webElementGuid>1d19a56d-4f9f-409d-b7c9-c393e80300f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sorry, your password was incorrect. Please double-check your password.']/parent::*</value>
      <webElementGuid>63bb9612-6d27-44c6-89b7-346ddb34899e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>6d0902f5-5bca-4ffb-9804-d80c11a4b1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'slfErrorAlert' and (text() = 'Sorry, your password was incorrect. Please double-check your password.' or . = 'Sorry, your password was incorrect. Please double-check your password.')]</value>
      <webElementGuid>56776484-3d26-47bf-b55f-f0ebdfaa4219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
